name: Call a reusable workflow

on: [push]

env:
  blah: schnoo

jobs:
  call-workflow-passing-data:
    uses: johndowns/workflow-playground-2/.github/workflows/called.yml@main
    with:
      username: ${{ env.blah }}
