name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

env:
  blah: schnoo

jobs:
  call-workflow-passing-data:
    uses: johndowns/workflow-playground-2/.github/workflows/called.yml@main
    with:
      username: ${{ env.blah }}
