name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      
jobs: 
  job1:
    runs-on: ubuntu-latest
    environment: Production # TODO should fail because this client ID is set up for test 
    outputs:
      appServiceAppName: ${{ steps.deploy.outputs.appServiceAppName }}
    steps:
    - uses: actions/checkout@v2
    - name: Installing CLI-beta for OpenID Connect
      run: |
        cd ../..
        CWD="$(pwd)"
        python3 -m venv oidc-venv
        . oidc-venv/bin/activate
        echo "activated environment"
        python3 -m pip install -q --upgrade pip
        echo "started installing cli beta"
        pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
        echo "***************installed cli beta*******************"
        echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
        
    - name: 'Az CLI login'
      uses: azure/login@v1.4.0
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

    - uses: azure/arm-deploy@v1
      id: deploy
      name: Deploy Bicep file
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: Playground1
        template: ./deploy/main.bicep

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps: 
    - run: |
        echo "${{needs.job1.outputs.appServiceAppName}}"
